version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: "app/Dockerfile"
    container_name: short-link-bot
    env_file:
      - ".env.docker"
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - short-link-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - short-link-network

networks:
  short-link-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
