version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: short-link-bot
    env_file:
      - ".env.local"
    depends_on:
      - mongo
    ports:
      - "8082:8080"
    networks:
      - short-link-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - short-link-network
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - bot
    restart: always
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - short-link-network


networks:
  short-link-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
